name: build release wasm

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Build optimised
        run: ./scripts/build_optimised_release.sh
      - name: Get release ID
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release wasm
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/juno_farm_hackathon_template.wasm
          asset_name: juno_farm_hackathon_template.wasm
          asset_content_type: application/octet-stream
      - name: Upload checksums
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain
